lec_11_django_forms_auth/csdprt/csdprt/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('persons/', include('persons.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lec_11_django_forms_auth/csdprt/persons/urls.py
from django.urls import path
from .views import *

app_name='persons'

urlpatterns = [
	path ('', index, name='index'),
	path ('all/', view_persons, name='all_persons'),
	path('<int:person_id>/', view_teacher_courses, name="teacher_course"),
	path('course/<slug:pk>/remove/', CourseDeleteView.as_view(), name="remove_course"),
	path('course/<slug:pk>/edit/', CourseUpdateView.as_view(), name="update_course"),
	path('course/all', CourseListView.as_view(), name='all_courses'),
	path('addcourse/', CourseCreateView.as_view(), name='add_course'),
]

lec_11_django_forms_auth/csdprt/persons/models.py
from django.db import models
from django.core import validators

class Person(models.Model):
	person_id = models.AutoField(primary_key=True)
	first_name = models.CharField(max_length=50, verbose_name="Имя")
	last_name = models.CharField(max_length=50, verbose_name="Фамилия")
	patronymic = models.CharField(max_length=50, null=True, blank=True)
	bio = models.TextField(null=True, blank=True, validators=[validators.MinLengthValidator(10, message="Биография должна быть не короче 10 символов")])
	email = models.EmailField(null=True, verbose_name="email адрес")
	publications = models.TextField(null=True, blank=True)
	photo = models.ImageField(upload_to ='uploads/', null=True, blank=True)

	def __str__(self):
		return f"{self.first_name} {self.patronymic} {self.last_name}"

	class Meta:
		verbose_name_plural='Преподаватели'
		verbose_name = 'Преподаватель'
		ordering = ['-last_name']


class Course(models.Model):
	course_id = models.AutoField(primary_key=True)
	name = models.CharField(max_length=50, verbose_name="Наименование дисциплины", db_index=True)
	description = models.TextField(null=True, blank=True, verbose_name="Описание", validators=[validators.MinLengthValidator(10, message="Биография должна быть не короче 10 символов")])
	learning_outcomes = models.TextField(null=True, blank=True, verbose_name="Приобретаемые навыки")
	mooc_url = models.URLField(null=True, error_messages={'invalid': 'Неправильно указан URL адрес'})
	person_id = models.ForeignKey('Person', null=True, on_delete=models.PROTECT, verbose_name='Преподаватель')

	class Meta :
		verbose_name_plural = 'Дисциплины'
		verbose_name = 'Дисциплина'
		ordering= ['name']

lec_11_django_forms_auth/csdprt/persons/forms.py
from django.forms import ModelForm
from .models import Person, Course


class CourseForm(ModelForm) :
    class Meta:
        model = Course
        fields = ('course_id', 'name', 'description', 'learning_outcomes', 'person_id')

lec_11_django_forms_auth/csdprt/persons/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Person, Course
from django.template import loader
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from django.urls import reverse_lazy
from .forms import CourseForm
from django.contrib.auth.models import Permission


def get_user_permissions(user):
    if user.is_superuser:
        return Permission.objects.all()
    return user.user_permissions.all() | Permission.objects.filter(group__user=user)

class CourseCreateView(CreateView):
	template_name = 'persons/create_course.html'
	form_class = CourseForm
	#success_url = "persons:all_persons"

	def get_context_data (self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['dummy'] = 5
		return context

	def get_success_url(self):
		return reverse_lazy("persons:teacher_course", kwargs={"person_id": self.object.person_id.person_id})

class CourseUpdateView(UpdateView):
	template_name = 'persons/create_course.html'
	model = Course
	form_class = CourseForm

	def get_context_data (self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['dummy'] = 5
		return context

	def get_success_url(self):
		return reverse_lazy("persons:teacher_course", kwargs={"person_id": self.object.person_id.person_id})

class CourseListView(ListView):
	model = Course
	queryset = Course.objects.order_by('-name')
	template_name = "persons/all_courses.html"

	def get_context_data(self, **kwargs):
		context = super(CourseListView, self).get_context_data(**kwargs)
		context['some_data'] = 'This is just some data!!!'
		return context

class CourseDeleteView(DeleteView):
	model = Course
	template_name = 'persons/course_delete.html'

	def get_success_url(self):
		return reverse_lazy("persons:teacher_course", kwargs={"person_id": self.object.person_id.person_id})

def index(request) :
	return render(request, "persons/index.html")

def view_persons(request):
	persons = Person.objects.order_by('-last_name')
	return render(request, "persons/persons.html", {'persons': persons})

def view_teacher_courses(request, person_id):
	courses = Course.objects.filter(person_id=person_id)
	teacher = Person.objects.get(pk=person_id)
	return render(request, "persons/teacher_courses.html", {'teacher': teacher, 'courses': courses}, content_type='text/html; charset=utf-8')

def remove_course(request, course_id):
	Course.objects.filter(pk=course_id).delete()
	return redirect('persons:index')

lec_11_django_forms_auth/csdprt/persons/templates/persons/all_courses.html
{% extends "header.html" %}

{% block title %}Все курсы{% endblock %}

{% block content %}

<h1>Курсы</h1>
<a href="{% url 'persons:add_course' %}">Добавить</a>
<div>
    {% for c in course_list %}
        <h3>{{ c.name }}</h3>
        <a href="{% url 'persons:remove_course' c.pk %}">Удалить</a>
        <a href="{% url 'persons:update_course' c.pk %}">Править</a>
        <div>{{ c.person_id }}</div>
        <div>{{ c.description }}</div>
        <div>{{ c.learning_outcomes }}</div>
    {% endfor %}

</div>
{% endblock %}

lec_11_django_forms_auth/csdprt/persons/templates/persons/course_delete.html
{% extends "header.html" %}

{% block title %}Дисциплины препоадвателя{% endblock %}

{% block content %}
<h2>Удаление дисциплины</h2>
    <form action="" method="post">{% csrf_token %}
      <p>Вы действительно хотите удалить дисциплину "{{ course.name }}"?</p>
      <input type="submit" value="Удалить" />
        <a href="{% url 'persons:index' %}">Отмена</a>
    </form>
{% endblock content %}

lec_11_django_forms_auth/csdprt/persons/templates/persons/create_course.html
{% extends "header.html" %}

{% block title %}Дисциплины препоадвателя{% endblock %}

{% block content %}

<h1>Добавление курса</h1>
<div>
    <a href=" {% url 'persons:index' %} ">Главная</a>
    <form method="post">
    {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" vаluе="Сохранить" />
    {{ dummy }}
</div>
</form>
{% endblock %}

lec_11_django_forms_auth/csdprt/persons/templates/persons/index.html
{% extends "header.html" %}

{% block title %}Факультет информационных систем и технологий{% endblock %}

{% block content %}
	<h1>Факультет информационных систем и технологий</h1>
{% endblock %}

lec_11_django_forms_auth/csdprt/persons/templates/persons/persons.html
{% extends "header.html" %}

{% block title %}Список преподавателей{% endblock %}

{% block content %}
	<h1>Сорудники</h1>
	{% for p in persons %}
	<div>
		<h2>{{ p.first_name }} {{ p.last_name }} {{ p.patronymic }}</h2>
		<div> {{ p.person_id }} </div>
		<img src="/uploads/{{ p.photo }}" alt="image" class="photo-img" />
		<div> {{ p.bio }} </div>
		<div> {{ p.publications}} </div>
		<div><a href="{% url 'persons:teacher_course' p.pk %}">Список дисциплин</a></div>
	</div>
	{% endfor %}
{% endblock %}

lec_11_django_forms_auth/csdprt/persons/templates/persons/teacher_courses.html
{% extends "header.html" %}

{% block title %}Дисциплины препоадвателя{% endblock %}
{% load bootstrap4 %}
{% block content %}

<h1>Преподаватель</h1>
<div>
    <h2>{{ teacher.first_name }} {{ teacher.last_name }} {{ teacher.patronymic }}</h2>
    <div>{{ teacher.bio }}</div>
    <div>
        {{ teacher.publications}}
    </div>
</div>
<h2>Список преподаваемых дисциплин</h2>
{% if perms.persons.add_course or user.email == teacher.email %}
<a href="{% url 'persons:add_course' %}">Добавить</a>
{% endif %}
<div>
    {% for c in courses %}
        <h3>{{ c.name }}</h3>
        {% if perms.persons.delete_course or user.email == teacher.email %}
            <a href="{% url 'persons:remove_course' c.pk %}">Удалить</a>
        {% endif %}
        {% if perms.persons.change_course or user.email == teacher.email %}
            <a href="{% url 'persons:update_course' c.pk %}">Править</a>
        {% endif %}
        <div>{{ c.description }}</div>
        <div>{{ c.learning_outcomes }}</div>
    {% endfor %}

</div>
{% endblock %}