lec_11_django_forms_auth/csdprt/accounts/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from .views import *
from .views import RegisterUserView, RegisterDoneView
from .views import user_activate


app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('profile/', profile, name='profile'),
    path('profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('logout/', LogoutView.as_view(next_page='persons:index'), name='logout'),
    path('register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('password_change/',
         AccountsPasswordChangeView.as_view(), name='password_change'),
    path('password_reset/',
         PasswordResetView.as_view(template_name='accounts/password_reset.html',
                                   subject_template_name='accounts/reset_subject.txt',
                                   email_template_name='accounts/reset_email.txt',
                                   success_url=reverse_lazy('accounts:password_reset_done')),
         name='password_reset'),
    path('password_reset/done/',
         PasswordResetDoneView.as_view(template_name='accounts/email_sent.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='accounts/confirm_password.html',
         success_url=reverse_lazy('accounts:password_reset_camplete')),
         name='password_reset_confirm'),
    path('reset/done/',
         PasswordResetCompleteView.as_view(template_name='accounts/password_confirmed.html'),
         name='password_reset_camplete'),
]

lec_11_django_forms_auth/csdprt/csdprt/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('persons/', include('persons.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lec_11_django_forms_auth/csdprt/accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.dispatch import Signal
from .utilities import send_activation_notification


class AdvUser(AbstractUser):
    phone = models.CharField(max_length=20, null=True, verbose_name="Номер телефона")
    patronymic = models.CharField(max_length=50, null=True,  verbose_name="Отчество")
    is_activated = models.BooleanField(default=True)
    send_messages = models.BooleanField(default=True, verbose_name='Слать оповещения о новых комментариях?')

    class Meta(AbstractUser.Meta):
        pass

user_registrated = Signal(providing_args=['instance'])


def user_registrated_dispatcher(sender, **kwargs):
    send_activation_notification(kwargs['instance'])


user_registrated.connect(user_registrated_dispatcher)

lec_11_django_forms_auth/csdprt/accounts/forms.py
from django import forms
from .models import AdvUser
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from .models import user_registrated


class ChangeUserinfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Aдpec электронной почты')
    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'patronymic', 'last_name' )

class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Пароль повторно', widget=forms.PasswordInput,
                                help_text='Повторите пороль')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError(
                'Введенные пороли не совпадают', code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        user_registrated.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'send_messages')

lec_11_django_forms_auth/csdprt/accounts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.signing import BadSignature
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.views.generic.base import TemplateView
from django.views.generic.edit import UpdateView, CreateView
from .utilities import signer
from .models import AdvUser
from .forms import ChangeUserinfoForm, RegisterUserForm


@login_required
def profile(request) :
    return render(request, 'accounts/profile.html')

class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView) :
    model = AdvUser
    template_name = 'accounts/change_user_info.html'
    form_class = ChangeUserinfoForm
    success_url = reverse_lazy('accounts:profile')
    success_message = 'Данные пользователя изменены'

    def setup(self, request, *args, **kwargs) :
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

class AccountsPasswordChangeView(PasswordChangeView):
    success_url = reverse_lazy('accounts:profile')
    template_name = 'accounts/password_change.html'


class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'accounts/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('accounts:register_done')


class RegisterDoneView(TemplateView):
    template_name = 'accounts/register_done.html'


def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'accounts/bad_signature.html')
    user = get_object_or_404(AdvUser, username=username)
    if user.is_activated:
        template = 'accounts/user_is_activated.html'
    else:
        template = 'accounts/activation_done.html'
        user.is_active = True
        user.is_activated = True
        user.save()
    return render(request, template)

lec_11_django_forms_auth/csdprt/accounts/templates/accounts/activation_done.html
{% extends "header.html" %}
{% block title %} Активация выполнена {% endblock%}
{% block content %}
<h2>Активация</h2>
<p>Пользователь с таким  именем успешно активирован.</p>
<p><a href="{% url 'accounts:login' %}">Войти на сайт</a></p>
{% endblock %}

lec_11_django_forms_auth/csdprt/accounts/templates/accounts/bad_signature.html
{% extends "layout/basic.html" %}
{% block title %} Ошибка при активации {% endblock%}
{% block content %}
<h2>Активация</h2>
<p>Ошибка активации</p>
<p><a href="{% url 'main:register' %}">Зарегистрироваться повторно</a></p>
{% endblock %}

lec_11_django_forms_auth/csdprt/accounts/templates/accounts/change_user_info.html
{% extends "header.html" %}
{% load bootstrap4 %}
{% block title %} Правка личных данных {% endblock %}

{% block content %}
<header class="bg-dark pt-9 pb-11 d-none d-md-block">
    <div class="container-md">
        <div class="row align-items-center">
            <div class="col">

                <!-- Heading -->
                <h1 class="fw-bold text-white mb-2">
                    Изменение данных профиля
                </h1>

            </div>
        </div> <!-- / .row -->
    </div> <!-- / .container -->
</header>
<div class="container-md">
    <div class="row">
        <div class="col-12 col-md-9">
            <div class="card card-bleed shadow-light-lg mb-6">
                <div class="card card-bleed shadow-light-lg mb-6">
                    <div class="card-header">Изменение данных пользователя {{user.username}}</div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {% bootstrap_form form layout='horizontal' %}
                            {% buttons submit='Сохранить' %}{% endbuttons %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

lec_11_django_forms_auth/csdprt/accounts/templates/accounts/confirm_password.html
{% extends "header.html" %}
{% load bootstrap4 %}
{% block title %} Восстановление пароля {% endblock %}

{% block content %}

{% if validlink %}

<h1>Set a new password!</h1>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Изменить пароль">
</form>

{% else %}

<p>Ссылка не верна. Попробуйте еще раз.</p>

{% endif %}
{% endblock %}

lec_11_django_forms_auth/csdprt/accounts/templates/accounts/email_sent.html
{% extends "header.html" %}
{% load bootstrap4 %}
{% block title %} Правка личных данных {% endblock %}

{% block content %}
<h2>Восстановление пароля</h2>
<form method="post">
    {% csrf_token %}
    Письмо с инструкциями отправлено на Ваш email
</form>
{% endblock %}

lec_11_django_forms_auth/csdprt/accounts/templates/accounts/login.html
{% extends "header.html" %}
{% block title %} Вход {% endblock %}
{% block content %}
<h2>Вход</h2>
{% if user.is_authenticated %}
<p>Вход был выполнен.</p>
{% else %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" name="text" value="{{ next }}">
    <input type="submit" value="Войти">
</form>
{% endif %}
{% endblock%}

lec_11_django_forms_auth/csdprt/accounts/templates/accounts/logout.html
{% extends "layout/basic.html" %}

{% block title %}Выход{% endblock %}

{% block content %}
<h2>Выход</h2>
<p>Вы покинули сайт</p>
{% endblock %}

lec_11_django_forms_auth/csdprt/accounts/templates/accounts/password_change.html
{% extends "header.html" %}

{% load bootstrap4 %}

{%block title%}Смена пороля{% endblock %}

{% block content %}
<h2>Смена пороля пользователя {{user.username}}</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Сменить пароль' %}{% endbuttons %}
</form>
{% endblock %}

lec_11_django_forms_auth/csdprt/accounts/templates/accounts/password_confirmed.html
{% extends "header.html" %}
{% load bootstrap4 %}
{% block title %} Восстановление пароля {% endblock %}

{% block content %}
  <h1>Пароль успешно изменен</h1>
{% endblock %}

lec_11_django_forms_auth/csdprt/accounts/templates/accounts/password_reset.html
{% extends "header.html" %}
{% load bootstrap4 %}
{% block title %} Правка личных данных {% endblock %}

{% block content %}
  <h1>Забыли пароль?</h1>
  <p>Введите свой email для получения инструкций</p>

  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <input type="submit" value="Отправить" />
  </form>
{% endblock %}

lec_11_django_forms_auth/csdprt/accounts/templates/accounts/profile.html
{% extends "header.html" %}
{% block title %} Профиль  пользователя {% endblock %}
{% block content %}
<h2>Профиль пользователя {{ user.username }}</h2>

{% if user.first_name and user.username %}
<p>Здравствуйте, {{ user.first_name }} {{ user.last_name }}!</p>
{% else %}
<p>Здравствуйте!</p>
{% endif %}
{% endblock %}

lec_11_django_forms_auth/csdprt/accounts/templates/accounts/register_done.html
{% extends "header.html" %}

{% block title %}Регистрация завершена{% endblock %}

{% block content %}
<h2>Регистрация </h2>
<p>Регистрация пользователя завершена. </p>
<p>На адрес вашей электронной почты отправлено письмо для активации</p>
{% endblock %}

lec_11_django_forms_auth/csdprt/accounts/templates/accounts/register_user.html
{% extends "header.html" %}
{% load bootstrap4 %}
{% block title %}Регистрация{% endblock %}

{% block content %}
<h2>Регистрация нового пользователя</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Зарегестрироваться' %}{% endbuttons %}
</form>
{% endblock %}

lec_11_django_forms_auth/csdprt/accounts/templates/accounts/user_is_activated.html
{% extends "header.html" %}
{% block title %} Пользователь уже активен {% endblock%}
{% block content %}
<h2>Активация</h2>
<p>Пользователь с таким  именем  уже был активирован.</p>
<p><a href="{% url 'accounts:login' %}">Войти на сайт</a></p>
{% endblock %}